mongodbUsernameBase64: ZGVicnVpdHM=
mongodbPasswordBase64: ZGVicnVpdHM=
mongodbDatabaseUrl: mongodb
secretName: debruits-secrets
configMapName: debruits-configmap
mongoExpressPort: 8081
mongoDbPort: 27017
mongoDbDatabase: debruits
mongoDbtrainCollection: train-raw
mongoDbtestCollection: test-raw
mongoDbtestCollectionEvolution: test-evolution
mongoDbmodelCollection: model
mongoDbtestCollectionInference: test-inference
mongoDbtestCollectionInferenceSuperResolution: test-inference-super-resolution
mongoDbtestCollectionEvolutionSuperResolution: test-evolution-super-resolution