mongodbUsernameBase64: ZGVicnVpdHM=
mongodbPasswordBase64: ZGVicnVpdHM=
mongoDbPort: 27017
mongoDbDatabase: debruits
mongoDbtrainCollection: train-raw
mongoDbtestCollection: test-raw
clusterNodeId: $CLUSTER_NODE_ID
mongoDbNodeportPort: 30000
model_config:
  N_EPOCHS: 5
  BATCH_SIZE: 1
image_config:
  DIM: 512
  BLUR: 30
  ENHANCED_WIDTH: 1024
  ENHANCED_HEIGHT: 1024
video_config:
  FPS: 5
timestamp: $TIMESTAMP