system_config:
  PIP_VERSION: pip3
  PYTHON_VERSION: python3
  SRC_PATH: ./src
  SCRIPT_FOLDER: inference
  VIDEO_PATH: /home/fabio/Videos/test.mp4
  REMOVE_BACKGROUND: /home/fabio/Videos/frames
data: "bairrodorego"
image_config:
  DIM: 512
  BLUR: 20
  ENHANCED_WIDTH: 1920
  ENHANCED_HEIGHT: 1080
video_config:
  FPS: 5
model_config:
  MODE: "start"
  INPUT_FILTER: "original"
  TARGET_FILTER: "slic-1000"
  N_EPOCHS: 1
  LEARNING_RATE: 0.0002
  BATCH_SIZE: 1
overlap-images: ["original_solarize", "original_slic-1000"]