data: "bairrodorego"
image_config:
  DIM: 512
  BLUR: 20
  ENHANCED_WIDTH: 1920
  ENHANCED_HEIGHT: 1080
video_config:
  FPS: 5
model_config:
  MODE: "continue"
  INPUT_FILTER: "original"
  TARGET_FILTER: "solarize"
  N_EPOCHS: 1
  LEARNING_RATE: 0.0002
  BATCH_SIZE: 1
system_config:
  PIP_VERSION: pip3
  PYTHON_VERSION: python3
  SRC_PATH: ./src
overlap-results: ["edges_sharpen", "slic-100_solarize"]