mongodbUsernameBase64: ZGVicnVpdHM=
mongodbPasswordBase64: ZGVicnVpdHM=
mongoDbPort: 27017
mongoDbDatabase: debruits
mongoDbtrainCollection: train-raw
mongoDbtestCollection: test-raw
clusterNodeId: 172.19.0.2
mongoDbNodeportPort: 30000
model_config:
  N_EPOCHS: 1
  BATCH_SIZE: 1
image_config:
  DIM: 1024
  BLUR: 20
  ENHANCED_WIDTH: 1024
  ENHANCED_HEIGHT: 512
  ENHANCEMENT_FACTOR: 2
video_config:
  FPS: 5
timestamp: 20240508_192015