system_config:
  PIP_VERSION: pip3
  PYTHON_VERSION: python3
model_config:
  MODE: "start"
  BRIGHTNESS: 1
  CONTRAST: 1
  BLUR: 20
  SATURATION: 1
  N_EPOCHS: 1
  INPUT_FILTER: "edges"
  TARGET_FILTER: "sharpen"
frames_to_video_config:
  FPS: 5
folder: "bairrodorego"
enhanced_width: 1920
enhanced_height: 1080
overlap-results: ["edges_sharpen", "slic-100_solarize"]