mongodbUsernameBase64: ZGVicnVpdHM=
mongodbPasswordBase64: ZGVicnVpdHM=
mongoDbPort: 27017
mongoDbDatabase: debruits
mongoDbtrainCollection: train-raw
mongoDbtestCollection: test-raw
clusterNodeId: $CLUSTER_NODE_ID
mongoDbNodeportPort: 30000
model_config:
  N_EPOCHS: 1
  BATCH_SIZE: 1
image_config:
  DIM: 1024
  BLUR: 20