
mongodbUsernameBase64: ZGVicnVpdHM=
mongodbPasswordBase64: ZGVicnVpdHM=
mongoDbPort: 27017
mongoDbDatabase: debruits
mongoDbtrainCollection: train-raw
mongoDbtestCollection: test-raw
model_config:
  INPUT_FILTER: "original"
  TARGET_FILTER: "edges"
  LEARNING_RATE: 0.001