system_config:
  SRC_PATH: ./src
  SUPER_RESOLUTION_FOLDER: evolution
  VIDEO_PATH: /home/fabio/Videos/test.mp4
  REMOVE_BACKGROUND: /home/fabio/Videos/frames
google_drive:
  service_account_json: debruits-2efd0b97327f.json
  main_id: 1MjIa29dGZi4DIDdTKQ-zIiR3REkE_Ivj
data: "bairrodorego"
image_config:
  DIM: 256
  BLUR: 20
  ENHANCED_WIDTH: 1920
  ENHANCED_HEIGHT: 1080
  ENHANCEMENT_FACTOR: 20
video_config:
  FPS: 5
model_config:
  INPUT_FILTER: "original"
  TARGET_FILTER: "solarize"
  N_EPOCHS: 1
  LEARNING_RATE: 0.0002
  BATCH_SIZE: 1
overlap-images: ["original_solarize", "original_slic-1000"]