services:
  app:
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /home/fabiocuri/Documents/DE BRUITS:/home/fabiocuri/Documents/DE BRUITS
      - ./webapp/config.json:/app/webapp/config.json
      - ./webapp/thumbnails.json:/app/webapp/thumbnails.json
