pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: python
            image: python:3.10.12
            command: ["cat"]
            args: []
            tty: true
            resources:
              requests:
                memory: "16Gi"
              limits:
                memory: "48Gi"
      '''
    }
  }
  parameters {
    choice(name: 'DATASET', choices: ['rego', 'parque'], description: 'Select dataset')
    choice(name: 'INPUT_FILTER', choices: ['original', 'solarize', 'slic-10', 'slic-100', 'slic-1000', 'color', 'gaussian', 'edges', 'blur', 'sharpen'], description: 'Select input filter')
    choice(name: 'TARGET_FILTER', choices: ['original', 'solarize', 'slic-10', 'slic-100', 'slic-1000', 'color', 'gaussian', 'edges', 'blur', 'sharpen'], description: 'Select target filter')
    choice(name: 'LEARNING_RATE', choices: ['0.01', '0.001', '0.0001'], description: 'Learning rate')
  }
  stages {
    stage('install-requirements') {
      steps {
        container('python') {
          sh 'pip install -r requirements.txt'
        }
      }
    }
    stage('data-download') {
      steps {
        container('python') {
          script {
            def DATASET = params.DATASET
            def INPUT_FILTER = params.INPUT_FILTER
            def TARGET_FILTER = params.TARGET_FILTER
            def LEARNING_RATE = params.LEARNING_RATE
            
            if (params.DATASET == 'rego') {
              sh 'gdown --id 1BPJQ1pRoCnUxYWP65Xklufgtl85kg1dD'
            } else if (params.DATASET == 'art') {
              sh 'gdown --id 1p_3PegnUsINvobi6pUF46rwVOEGc_LpC'
            }
          sh 'unzip data.zip && rm -rf data.zip'
          }
        }
      }
    }
    stage('data-encode') {
      steps {
        container('python') {
          sh "python src/encode_images.py $DATASET"
        }
      }
    }
    stage('data-preprocess') {
      steps {
        container('python') {
          script {
            sh "python src/preprocess.py jenkins $DATASET $INPUT_FILTER $TARGET_FILTER $LEARNING_RATE"
          }
        }
      }
    }
    stage('model-train') {
      steps {
        container('python') {
          sh "python src/train_gan.py jenkins $DATASET $INPUT_FILTER $TARGET_FILTER $LEARNING_RATE"
        }
      }
    }
    stage('model-inference') {
      steps {
        container('python') {
          sh "python src/inference.py jenkins $DATASET $INPUT_FILTER $TARGET_FILTER $LEARNING_RATE"
        }
      }
    }
    stage('create-video') {
      steps {
        container('python') {
          sh "python src/create_video.py jenkins data/sequence_borosylicate $DATASET $INPUT_FILTER $TARGET_FILTER $LEARNING_RATE"
        }
      }
    }
    stage('send-email') {
      steps {
        container('python') {
          script {
            emailext(
              attachLog: true,
              body: 'Please find the attached videos generated by Jenkins.',
              subject: "De Bruits ($DATASET-$INPUT_FILTER-$TARGET_FILTER-$LEARNING_RATE)",
              from: 'debruitsproject@gmail.com',
              to: 'debruitsproject@gmail.com',
              attachmentsPattern: '**/*.mp4,**/source_example.png,**/target_example.png'
            )
          }
        }
      }
    }
  }
}