apiVersion: v1
data:
  config.json: |-
    {
      "back_footer": {
        "pt": "DE BRUITS É UM PROJETO QUE ACREDITA EM UM FUTURO MAIS ANALÓGICO, ONDE AS PESSOAS SE RECONECTAM E REDESCOBREM O PAPEL.\n\nO PAPEL QUE VOCÊ ESTÁ SEGURANDO FOI PRODUZIDO ARTESANALMENTE. TODO O PAPEL UTILIZADO PARA A RECICLAGEM FOI OBTIDO LOCALMENTE POR MEIO DE FEIRAS DE ANTIGUIDADES, COMPRAS INFORMAIS E DOAÇÕES. DESSA FORMA, APOIAMOS AS COMUNIDADES LOCAIS AO RESGATAR LIVROS QUE ESTÃO MUITO VELHOS, DESATUALIZADOS OU QUE DIFICILMENTE SERIAM VENDIDOS, DANDO AO PAPEL UMA NOVA FINALIDADE.",
        "en": "DE BRUITS IS A PROJECT THAT BELIEVES IN A MORE ANALOG FUTURE, WHERE PEOPLE RECONNECT AND REDISCOVER PAPER.\n\nTHE PAPER YOU ARE HOLDING WAS HANDCRAFTED. ALL THE PAPER USED FOR RECYCLING WAS SOURCED LOCALLY THROUGH ANTIQUE FAIRS, INFORMAL PURCHASES AND DONATIONS. THIS WAY, WE SUPPORT LOCAL COMMUNITIES BY RESCUING BOOKS THAT ARE TOO OLD, OUTDATED OR UNLIKELY TO BE SOLD, GIVING THE PAPER A NEW PURPOSE.",
        "es": "DE BRUITS ES UN PROYECTO QUE CREE EN UN FUTURO MÁS ANALÓGICO, DONDE LAS PERSONAS SE RECONECTAN Y REDESCUBREN EL PAPEL.\n\nEL PAPEL QUE ESTÁS SOSTENIENDO FUE PRODUCIDO ARTESANALMENTE. TODO EL PAPEL UTILIZADO PARA EL RECICLAJE FUE OBTENIDO LOCALMENTE A TRAVÉS DE FERIAS DE ANTIGÜEDADES, COMPRAS INFORMALES Y DONACIONES. DE ESTA MANERA, APOYAMOS A LAS COMUNIDADES LOCALES AL RESCATAR LIBROS QUE ESTÁN MUY VIEJOS, DESACTUALIZADOS O QUE DIFÍCILMENTE SERÍAN VENDIDOS, DANDO AL PAPEL UN NUEVO PROPÓSITO.",
        "fr": "DE BRUITS EST UN PROJET QUI CROIT EN UN FUTUR PLUS ANALOGIQUE, OÙ LES GENS SE RECONNECTENT ET REDÉCOUVRENT LE PAPIER.\n\nLE PAPIER QUE VOUS TENEZ A ÉTÉ PRODUIT ARTISANALEMENT. TOUT LE PAPIER UTILISÉ POUR LE RECYCLAGE A ÉTÉ OBTENU LOCALEMENT DANS DES MARCHÉS AUX PUCES, DES ACHATS INFORMELS ET DES DONS. AINSI, NOUS SOUTENONS LES COMMUNAUTÉS LOCALES EN SAUVANT DES LIVRES TROP VIEUX, DÉPASSÉS OU QUI NE SERAIENT PAS FACILEMENT VENDUS, DONNANT AU PAPIER UNE NOUVELLE FINALITÉ."
      },
      "back_description": {
        "pt": "DE BRUITS É UM PROJETO QUE ACREDITA EM UM FUTURO MAIS ANALÓGICO, ONDE AS PESSOAS SE RECONECTAM E REDESCOBREM O PAPEL.\n\nO FANZINE QUE VOCÊ ESTÁ SEGURANDO FOI PRODUZIDO ARTESANALMENTE. TODO O PAPEL UTILIZADO PARA A RECICLAGEM FOI OBTIDO LOCALMENTE POR MEIO DE FEIRAS DE ANTIGUIDADES, COMPRAS INFORMAIS E DOAÇÕES. DESSA FORMA, APOIAMOS AS COMUNIDADES LOCAIS AO RESGATAR LIVROS QUE ESTÃO MUITO VELHOS, DESATUALIZADOS OU QUE DIFICILMENTE SERIAM VENDIDOS, DANDO AO PAPEL UMA NOVA FINALIDADE.",
        "en": "DE BRUITS IS A PROJECT THAT BELIEVES IN A MORE ANALOG FUTURE, WHERE PEOPLE RECONNECT AND REDISCOVER PAPER.\n\nTHE FANZINE YOU ARE HOLDING WAS HANDCRAFTED. ALL THE PAPER USED FOR RECYCLING WAS SOURCED LOCALLY THROUGH ANTIQUE FAIRS, INFORMAL PURCHASES AND DONATIONS. THIS WAY, WE SUPPORT LOCAL COMMUNITIES BY RESCUING BOOKS THAT ARE TOO OLD, OUTDATED OR UNLIKELY TO BE SOLD, GIVING THE PAPER A NEW PURPOSE.",
        "es": "DE BRUITS ES UN PROYECTO QUE CREE EN UN FUTURO MÁS ANALÓGICO, DONDE LAS PERSONAS SE RECONECTAN Y REDESCUBREN EL PAPEL.\n\nEL FANZINE QUE ESTÁS SOSTENIENDO FUE PRODUCIDO ARTESANALMENTE. TODO EL PAPEL UTILIZADO PARA EL RECICLAJE FUE OBTENIDO LOCALMENTE A TRAVÉS DE FERIAS DE ANTIGÜEDADES, COMPRAS INFORMALES Y DONACIONES. DE ESTA MANERA, APOYAMOS A LAS COMUNIDADES LOCALES AL RESCATAR LIBROS QUE ESTÁN MUY VIEJOS, DESACTUALIZADOS O QUE DIFÍCILMENTE SERÍAN VENDIDOS, DANDO AL PAPEL UN NUEVO PROPÓSITO.",
        "fr": "DE BRUITS EST UN PROJET QUI CROIT EN UN FUTUR PLUS ANALOGIQUE, OÙ LES GENS SE RECONNECTENT ET REDÉCOUVRENT LE PAPIER.\n\nLE FANZINE QUE VOUS TENEZ A ÉTÉ PRODUIT ARTISANALEMENT. TOUT LE PAPIER UTILISÉ POUR LE RECYCLAGE A ÉTÉ OBTENU LOCALEMENT DANS DES MARCHÉS AUX PUCES, DES ACHATS INFORMELS ET DES DONS. AINSI, NOUS SOUTENONS LES COMMUNAUTÉS LOCALES EN SAUVANT DES LIVRES TROP VIEUX, DÉPASSÉS OU QUI NE SERAIENT PAS FACILEMENT VENDUS, DONNANT AU PAPIER UNE NOUVELLE FINALITÉ."
      },
      "data_root": "/data",
      "formats": {
        "mini-poster": {
          "has_back": true,
          "size_px": [
            3898,
            6378
          ]
        },
        "postcard": {
          "has_back": true,
          "size_px": [
            2480,
            3898
          ]
        },
        "poster": {
          "has_back": true,
          "size_px": [
            4961,
            7205
          ]
        }
      },
      "info_dashboard_url": "http://localhost:5001",
      "layout": {
        "front_gap": 0.01,
        "front_margin": 0.02,
        "hline_x0": 0.05,
        "hline_x1": 0.33,
        "hline_y": 0.908,
        "line_width": 4,
        "stamp_bottom": 0.012,
        "stamp_right": 0.02,
        "stamp_size": 0.048,
        "title_size": 0.018,
        "title_x": 0.05,
        "title_y": 0.916,
        "vline_x": 0.932,
        "vline_y0": 0.06,
        "vline_y1": 0.94
      },
      "series_title_options": {
        "ALGAS": {
          "pt": [
            "MFSAPIOFJPOFAM KKK",
            "sdasdsadasds"
          ]
        },
        "CONCHAS": {
          "pt": [
            "bbbbbbb"
          ]
        }
      },
      "series_titles": {
        "ALGAS": {
          "pt": [
            "ALGAS DE PERNAMBUCO"
          ],
          "en": [
            "ALGAE FROM PERNAMBUCO"
          ],
          "es": [
            "ALGAS DE PERNAMBUCO"
          ],
          "fr": [
            "ALGUES DE PERNAMBUCO"
          ]
        },
        "CONCHAS": {
          "pt": [
            "CONCHAS DE PERNAMBUCO"
          ],
          "en": [
            "SHELLS FROM PERNAMBUCO"
          ],
          "es": [
            "CONCHAS DE PERNAMBUCO"
          ],
          "fr": [
            "COQUILLAGES DE PERNAMBUCO"
          ]
        },
        "FRUTAS": {
          "pt": [
            "FRUTAS DE PERNAMBUCO"
          ],
          "en": [
            "FRUITS FROM PERNAMBUCO"
          ],
          "es": [
            "FRUTAS DE PERNAMBUCO"
          ],
          "fr": [
            "FRUITS DE PERNAMBUCO"
          ]
        },
        "PLANTAS": {
          "pt": [
            "PLANTAS MARINHAS DE PERNAMBUCO"
          ],
          "en": [
            "MARINE PLANTS FROM PERNAMBUCO"
          ],
          "es": [
            "PLANTAS MARINAS DE PERNAMBUCO"
          ],
          "fr": [
            "PLANTES MARINES DE PERNAMBUCO"
          ]
        }
      }
    }
kind: ConfigMap
metadata:
  name: debruits-config
