apiVersion: v1
kind: Service
metadata:
  name: debruits
  labels:
    app: debruits
spec:
  type: NodePort
  selector:
    app: debruits
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
